
import re
from pathlib import Path

from ..mcp_server import mcp
from ..utils import get_workspace, logger

@mcp.tool()
def read_metrics(project_name: str, report_file: str) -> str:
    """
    Read a report file and extract PPA metrics (Area, WNS, TNS, Cell Count).

    Supports text, CSV, and .rpt files generated by Yosys, OpenROAD, or OpenLane.

    Args:
        project_name: Project containing the reports.
        report_file: Relative path to the report (e.g. reports/synth_stats.txt).
    """
    try:
        ws = get_workspace(project_name)
    except ValueError as exc:
        return f"ERROR: {exc}"

    clean_path = Path(report_file)
    if ".." in clean_path.parts:
        return "ERROR: Report path must not contain '..' components."

    target = ws / clean_path
    if not target.exists():
        available = sorted(
            str(p.relative_to(ws))
            for p in ws.rglob("*")
            if p.is_file() and p.suffix in (".txt", ".csv", ".rpt", ".log", ".def", ".v")
        )
        avail_list = "\n".join(f"  - `{a}`" for a in available[:25])
        return (
            f"ERROR: Report file not found: `{target}`\n\n"
            f"### Available files\n{avail_list or '  (none)'}\n"
        )

    content = target.read_text(encoding="utf-8", errors="replace")

    # Extract PPA metrics
    metrics: dict[str, str | None] = {
        "area_um2": None, "wns": None, "tns": None, "cell_count": None
    }

    area_m = re.search(r"(?:Chip area|Design area)[:\s]+([0-9.]+)", content, re.IGNORECASE)
    if area_m:
        metrics["area_um2"] = area_m.group(1)
    wns_m = re.search(r"wns\s+([-0-9.]+)", content, re.IGNORECASE)
    if wns_m:
        metrics["wns"] = wns_m.group(1)
    tns_m = re.search(r"tns\s+([-0-9.]+)", content, re.IGNORECASE)
    if tns_m:
        metrics["tns"] = tns_m.group(1)
    cell_m = re.search(r"Number of cells:\s+(\d+)", content, re.IGNORECASE)
    if cell_m:
        metrics["cell_count"] = cell_m.group(1)

    found_metrics = {k: v for k, v in metrics.items() if v is not None}

    max_display = 3000
    if len(content) > max_display:
        half = max_display // 2 - 60
        display = (
            content[:half]
            + f"\n\n... [TRUNCATED — {len(content) - max_display:,} chars omitted] ...\n\n"
            + content[-half:]
        )
    else:
        display = content

    metrics_block = ""
    if found_metrics:
        rows = "\n".join(
            f"| {k.replace('_', ' ').title()} | `{v}` |"
            for k, v in found_metrics.items()
        )
        metrics_block = (
            f"\n### Extracted PPA Metrics\n"
            f"| Metric | Value |\n|--------|-------|\n{rows}\n"
        )

    return (
        f"## 📄 Report: `{report_file}`\n\n"
        f"- **Path:** `{target}`\n"
        f"- **Size:** {target.stat().st_size:,} bytes\n"
        f"{metrics_block}\n"
        f"### Content\n```\n{display}\n```\n"
    )
